/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TripSetupRouteImport } from './routes/trip-setup'
import { Route as TravelHistoryRouteImport } from './routes/travel-history'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as GeneratingRouteImport } from './routes/generating'
import { Route as IndexRouteImport } from './routes/index'

const TripSetupRoute = TripSetupRouteImport.update({
  id: '/trip-setup',
  path: '/trip-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelHistoryRoute = TravelHistoryRouteImport.update({
  id: '/travel-history',
  path: '/travel-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratingRoute = GeneratingRouteImport.update({
  id: '/generating',
  path: '/generating',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/generating': typeof GeneratingRoute
  '/preferences': typeof PreferencesRoute
  '/results': typeof ResultsRoute
  '/travel-history': typeof TravelHistoryRoute
  '/trip-setup': typeof TripSetupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/generating': typeof GeneratingRoute
  '/preferences': typeof PreferencesRoute
  '/results': typeof ResultsRoute
  '/travel-history': typeof TravelHistoryRoute
  '/trip-setup': typeof TripSetupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/generating': typeof GeneratingRoute
  '/preferences': typeof PreferencesRoute
  '/results': typeof ResultsRoute
  '/travel-history': typeof TravelHistoryRoute
  '/trip-setup': typeof TripSetupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/generating'
    | '/preferences'
    | '/results'
    | '/travel-history'
    | '/trip-setup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/generating'
    | '/preferences'
    | '/results'
    | '/travel-history'
    | '/trip-setup'
  id:
    | '__root__'
    | '/'
    | '/generating'
    | '/preferences'
    | '/results'
    | '/travel-history'
    | '/trip-setup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GeneratingRoute: typeof GeneratingRoute
  PreferencesRoute: typeof PreferencesRoute
  ResultsRoute: typeof ResultsRoute
  TravelHistoryRoute: typeof TravelHistoryRoute
  TripSetupRoute: typeof TripSetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trip-setup': {
      id: '/trip-setup'
      path: '/trip-setup'
      fullPath: '/trip-setup'
      preLoaderRoute: typeof TripSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel-history': {
      id: '/travel-history'
      path: '/travel-history'
      fullPath: '/travel-history'
      preLoaderRoute: typeof TravelHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generating': {
      id: '/generating'
      path: '/generating'
      fullPath: '/generating'
      preLoaderRoute: typeof GeneratingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GeneratingRoute: GeneratingRoute,
  PreferencesRoute: PreferencesRoute,
  ResultsRoute: ResultsRoute,
  TravelHistoryRoute: TravelHistoryRoute,
  TripSetupRoute: TripSetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
